### ISSUE TITLE
Drawer too-fast reopening overanimation

### ISSUE THREAD

**Issue by bryanchun** [danvim/Procal#64] opened 2017-02-22 04:09 UTC
Set state such that
```
if drawerState ="open"
Then onClick(){ closeDrawer(); }
else if drawerState = "closING"
Then onClick() { **openDrawer();** }
else // drawerState = "closed"
Then onClick(){ openDrawer(); }
```

Which is:
```java
if (drawerState = "open"){
    @override onClick(){
        closeDrawer();
    }
} else { // drawerState = "closed" including "closING"
    @override onClick(){
        openDrawer();
    }
}
```

Instead of
```
if drawerState ="open"
Then onClick(){ closeDrawer(); }
else if drawerState = "closING"
Then onClick() { **closeDrawer();** }
else // drawerState = "closed"
Then onClick(){ openDrawer(); }
```

**Comment by danvim** [comment] 2017-02-22 05:04
Duplicate of #54. Please move idea over there

**Closed as completed by danvim** 2017-02-22 05:04 UTC
Labels: bug, duplicate
